import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; // Adjust the path as needed
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="w-full bg-white  md:px-8 lg:px-16 xl:px-24 2xl:px-32 fg-black text-black fg-dark">
            <Navbar />
          </div>
          <div className="w-full bg-slate-100  md:px-8 lg:px-16 xl:px-24 2xl:px-32">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
